language: python
sudo: false
env:
  matrix:
  - TEST_DOCTESTS="true" FASTCACHE="false" TEST_SETUP="true"
  - SPLIT="1/4" TEST_SYMPY="true"
  - SPLIT="2/4" TEST_SYMPY="true"
  - SPLIT="3/4" TEST_SYMPY="true"
  - SPLIT="4/4" TEST_SYMPY="true"
  global:
    - secure: "YIEZal9EBTL+fg2YmoZoS8Bvt3eAVUOZjb38CtqpzR2CCSXWoUk35KG23m2NknlY1iKfYJyt7XWBszT/VKOQEbWQq7PIakV4vIByrWacgBxy1x3WC+rZoW7TX+JJiL+y942qIYbMoNMMB8xFpE5RDLSjSecMpFhJJXoafVTvju8="
dist: trusty

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env:
        - TEST_ASCII="true"
        - TEST_OPT_DEPENDENCY="numpy scipy gmpy2 matplotlib theano llvmlite autowrap python-symengine=0.3.* tensorflow"
      addons:
        apt:
          packages:
            # for theano
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - python-scipy

    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="1/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="2/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="3/3"

before_install:
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - |
    if [[ "${TEST_OPT_DEPENDENCY}" ]]; then
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -q -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -q -O miniconda.sh;
        fi
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
        hash -r;
        conda config --set always_yes yes --set changeps1 no;
        conda update -q conda;
        conda config --prepend channels conda-forge --prepend channels symengine/label/dev;
        conda info -a;
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip ${TEST_OPT_DEPENDENCY/autowrap/libgfortran libgcc gcc cython};
        source activate test-environment;
    elif [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then
        pip list --format=legacy | grep "numpy" && pip uninstall -y numpy;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matchpy;
    fi
install:
  # If a command fails, fail the build.
  - set -e
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ];
      then virtualenv -p /usr/bin/pypy ~/.venv;
           . ~/.venv/bin/activate;
    fi
script:
  # Don't run doctr if the build fails
  - set -e
  - bin/test_travis.sh
notifications:
  email: false
