language: python
sudo: false
env:
  matrix:
  - TEST_DOCTESTS="true" FASTCACHE="false" TEST_SETUP="true"
  - SPLIT="1/4" TEST_SYMPY="true"
  - SPLIT="2/4" TEST_SYMPY="true"
  - SPLIT="3/4" TEST_SYMPY="true"
  - SPLIT="4/4" TEST_SYMPY="true"
  global:
    - secure: "YIEZal9EBTL+fg2YmoZoS8Bvt3eAVUOZjb38CtqpzR2CCSXWoUk35KG23m2NknlY1iKfYJyt7XWBszT/VKOQEbWQq7PIakV4vIByrWacgBxy1x3WC+rZoW7TX+JJiL+y942qIYbMoNMMB8xFpE5RDLSjSecMpFhJJXoafVTvju8="
dist: trusty

python:
  - 2.7
  - 3.6

matrix:
  include:
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="1/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="2/3"
    - python: 3.6
      env:
        - TEST_SLOW="true"
        - SPLIT="3/3"

before_install:
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - |
    if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then
        pip list --format=legacy | grep "numpy" && pip uninstall -y numpy;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matchpy;
    fi
install:
  # If a command fails, fail the build.
  - set -e
  # -We:invalid makes invalid escape sequences error in Python 3.6. See
  # -#12028.
  - |
    if [[ "${TEST_SAGE}" != "true" ]]; then
      pip install mpmath;
      if [[ "${TEST_SETUP}" == "true" ]]; then
      # The install cycle below is to test installation on systems without setuptools.
        pip uninstall -y setuptools;
        python -We:invalid setup.py install;
        pip uninstall -y sympy;
        pip install --upgrade setuptools;
      fi
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py install;
      pip list --format=columns;
    fi
script:
  # Don't run doctr if the build fails
  - set -e
  - bin/test_travis.sh
notifications:
  email: false
